name: metadata

version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  event_meta_value_type:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/types/event_meta_value
  mappable:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/mixins/mappable
  key:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/key

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
