name: choose_wallet_verification_type_artboard
version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  spaced_column_vertical_floating_artboard_template:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboard_templates/vertical_floating/spaced_column
  app_data:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/app_data
  button_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/button
  navigator:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/navigator
  spaced_column_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/spaced_column
  choose_business_type_artboard:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboards/sustainers/choose_business_type
  verify_personal_wallet_artboard:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboards/sustainers/verify_personal_wallet

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
