name: task_type

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  string_from_enum_string:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: lib/string_from_enum_string

dev_dependencies:
  flutter_test:
    sdk: flutter
