name: invoice_info_floating_artboard_template
description: A stack artboard for displaying invoice info and an edit button.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  artboard:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: lib/artboard
  spaced_column_vertical_floating_artboard_template:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: artboard_templates/vertical_floating/spaced_column
  nav_bar_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: builders/nav_bar
  button_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: builders/button
  caret_wrap_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: builders/caret_wrap
  breadcrumb_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: builders/breadcrumb
  spaced_list_view_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: builders/spaced_list_view
  tag_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: builders/tag
  key_value_row_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: builders/key_value_row
  tab:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: tab
  navigation_icon_library:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: icons/navigation
  x_small_icon_library:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: icons/x_small
  standard_icon_library:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: icons/standard
  mask:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: lib/mask
  schedule:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: model/properties/schedule
  date:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: lib/date
  fee_payer_type:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: types/fee_payer

dependency_overrides:
  spaced_column_vertical_floating_artboard_template:
    path: ../../../artboard_templates/vertical_floating/spaced_column
  spaced_column_builder:
    path: ../../../builders/spaced_column
  nav_bar_builder:
    path: ../../../builders/nav_bar
  button_builder:
    path: ../../../builders/button
  caret_wrap_builder:
    path: ../../../builders/caret_wrap
  breadcrumb_builder:
    path: ../../../builders/breadcrumb
  spaced_list_view_builder:
    path: ../../../builders/spaced_list_view
  tag_builder:
    path: ../../../builders/tag
  key_value_row_builder:
    path: ../../../builders/key_value_row

dev_dependencies:
  flutter_test:
    sdk: flutter
