name: button_builder
description: Buttons

version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  standard_icon_library:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/icons/standard
  x_small_icon_library:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/icons/x_small
  tappable:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/lib/tappable
  haptics:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/lib/haptics
  typedefs:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/lib/typedefs
  button_status_option:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/options/button_status
  image_picker_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/builders/image_picker
  vertically_centered_text_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/builders/vertically_centered_text
  semantic_theme:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/semantic_theme

dev_dependencies:
  flutter_test:
    sdk: flutter
