name: breadcrumb_builder
description: Row with title and optional icon.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  x_small_icon_library:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: icons/x_small
  haptics:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: lib/haptics
  semantic_theme:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: semantic_theme

dependency_overrides:
  semantic_theme:
    path: ../../semantic_theme

dev_dependencies:
  flutter_test:
    sdk: flutter
