name: dwolla_model

version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  dwolla_types:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/types/dwolla

# dependency_overrides:
#   dwolla_types:
#     path: ../../types/dwolla

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
