name: frequency_type

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  period_type:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: types/period
  labeled_value:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: labeled_value

dev_dependencies:
  flutter_test:
    sdk: flutter
