name: titled_table_vertical_full_screen_artboard_template
description: A vertical full screen frame with a titled nav bar and a table for building a widget hierarchy in.
version: 1.0.0+1
environment:
  sdk: ^3.7.2
resolution: workspace
publish_to: none
dependencies:
  flutter:
    sdk: flutter
  artboard:
  vertical_full_screen_artboard_scaffold:
  nav_bar_builder:
  table_builder:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
