name: roof

version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  domain:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/abstract/domain
  balance:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/properties/balance
  domain_user:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/properties/domain_user
  location:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/properties/location
  date:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/lib/date
  key:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/key

dev_dependencies:
  flutter_test:
    sdk: flutter
