name: monorepo
description: The monorepo.

version: 1.0.0+1

environment:
  sdk: ^3.7.2

workspace:
  - components/svg
  - components/blossm_command
  - components/app_data
  - components/options/vertical_floating_artboard_button
  - components/options/tag_kind
  - components/options/button_status
  - components/artboards/meta_form
  - components/artboards/date_picker
  - components/artboards/sustainers/verify_sole_proprietorship_wallet
  - components/artboards/sustainers/balance_actions
  - components/artboards/sustainers/verify_business_wallet
  - components/artboards/sustainers/verify_personal_wallet
  - components/artboards/sustainers/choose_wallet_verification_type
  - components/artboards/sustainers/choose_business_type
  - components/artboards/roller_column_picker
  - components/artboards/time_picker
  - components/artboards/interval_frequency_picker
  - components/artboards/option_picker
  - components/artboards/icon_picker
  - components/artboards/tag_editor
  - components/types/event_meta_value
  - components/types/expense
  - components/types/billing_status
  - components/types/dwolla
  - components/types/contract
  - components/types/context
  - components/types/privacy
  - components/types/commentable_object
  - components/types/sort
  - components/types/frequency
  - components/types/bank
  - components/types/transfer_status
  - components/types/transfer
  - components/types/completion
  - components/types/assignment
  - components/types/period
  - components/types/push_token
  - components/types/fee_payer
  - components/types/lease
  - components/types/notification_embedded_object
  - components/types/event_object
  - components/types/email_category
  - components/types/payment_default
  - components/types/bank_owner
  - components/types/task
  - components/types/stub
  - components/types/notification_category
  - components/types/request
  - components/types/bank_status
  - components/types/day
  - components/types/invitation
  - components/types/property_icon
  - components/types/thread
  - components/types/domain
  - components/types/event
  - components/types/billing
  - components/types/invoice
  - components/types/us_state
  - components/semantic_theme
  - components/artboard_templates/vertical_full_screen/empty
  - components/artboard_templates/vertical_full_screen/stream_list_view
  - components/artboard_templates/vertical_full_screen/scroll_view
  - components/artboard_templates/vertical_full_screen/tabbed
  - components/artboard_templates/vertical_full_screen/titled_table
  - components/artboard_templates/vertical_full_screen/empty_table
  - components/artboard_templates/vertical_full_screen/thread
  - components/artboard_templates/vertical_full_screen/full_logo_table
  - components/artboard_templates/vertical_drawer/nav_drawer
  - components/artboard_templates/horizontal_floating/empty
  - components/artboard_templates/horizontal_floating/object
  - components/artboard_templates/vertical_floating/form
  - components/artboard_templates/vertical_floating/empty
  - components/artboard_templates/vertical_floating/spaced_column
  - components/builders/meta_form
  - components/builders/form
  - components/builders/date_picker
  - components/builders/caret_wrap
  - components/builders/view_stream_builder
  - components/builders/spaced_list_view
  - components/builders/tabbed_container
  - components/builders/input_dock
  - components/builders/form_body
  - components/builders/keyboard_accessory_bar
  - components/builders/icon_button
  - components/builders/nav_bar
  - components/builders/roller_column
  - components/builders/roller_column_picker
  - components/builders/image_picker
  - components/builders/spaced_column
  - components/builders/time_picker
  - components/builders/nav_button
  - components/builders/button
  - components/builders/interval_frequency_picker
  - components/builders/thread_list_view
  - components/builders/table
  - components/builders/vertically_centered_text
  - components/builders/key_value_row
  - components/builders/option_picker
  - components/builders/icon_picker
  - components/builders/spaced_grid
  - components/builders/key_value
  - components/builders/table_cell
  - components/builders/breadcrumb
  - components/builders/button_row_dock
  - components/builders/tag
  - components/builders/tag_editor
  - components/builders/header
  - components/spec/color
  - components/spec/distance
  - components/spec/curve
  - components/spec/typography
  - components/spec/padding
  - components/spec/duration
  - components/spec/corner_radius
  - components/tab
  - components/theme
  - components/icons/icon_reference
  - components/icons/navigation
  - components/icons/small
  - components/icons/standard
  - components/icons/x_small
  - components/model/abstract/transaction
  - components/model/abstract/contract
  - components/model/abstract/context
  - components/model/abstract/domain_object
  - components/model/abstract/commentable_object
  - components/model/abstract/one_to_one_transaction
  - components/model/abstract/feed_object
  - components/model/abstract/model_object
  - components/model/abstract/task
  - components/model/abstract/domain
  - components/model/dwolla
  - components/model/mixins/name_defining_object
  - components/model/mixins/mappable
  - components/model/objects/organization
  - components/model/objects/expense
  - components/model/objects/lease_preview
  - components/model/objects/settlement
  - components/model/objects/property
  - components/model/objects/comment
  - components/model/objects/reminder
  - components/model/objects/transfer
  - components/model/objects/completion
  - components/model/objects/user
  - components/model/objects/lease
  - components/model/objects/public
  - components/model/objects/stub
  - components/model/objects/roof
  - components/model/objects/service_request
  - components/model/objects/thread
  - components/model/objects/event
  - components/model/objects/shopping_item
  - components/model/objects/invoice
  - components/model/key
  - components/model/properties/bank_owner_reference
  - components/model/properties/schedule
  - components/model/properties/actor_reference
  - components/model/properties/user_reference
  - components/model/properties/payer
  - components/model/properties/location
  - components/model/properties/name_payment_profile
  - components/model/properties/late_fee
  - components/model/properties/splitter
  - components/model/properties/balance
  - components/model/properties/name_domain
  - components/model/properties/contract_user
  - components/model/properties/thread_reference
  - components/model/properties/domain_user
  - components/model/properties/task_reference
  - components/model/properties/completion_count
  - components/model/properties/payment_default
  - components/model/properties/name_property
  - components/model/properties/date_parts
  - components/model/properties/name_user
  - components/model/properties/name_contract_domain
  - components/model/properties/name_context
  - components/model/properties/metadata
  - components/model/properties/name_contract
  - components/model/properties/billing
  - components/model/properties/expense_part
  - components/model/properties/commentable_object_reference
  - components/model/name_formatter
  - components/model/object_cache
  - components/labeled_value
  - components/artboard_scaffolds/vertical_full_screen
  - components/artboard_scaffolds/vertical_drawer
  - components/artboard_scaffolds/horizontal_floating
  - components/artboard_scaffolds/vertical_floating
  - components/lib/ordinal_suffix_string_from_int
  - components/lib/stringify_names
  - components/lib/haptics
  - components/lib/form
  - components/lib/tappable
  - components/lib/cache
  - components/lib/interval
  - components/lib/stream
  - components/lib/date
  - components/lib/network
  - components/lib/artboard
  - components/lib/typedefs
  - components/lib/mask
  - components/lib/device_screen
  - components/lib/string_from_enum_string
  - components/lib/table
  - components/lib/form_validation_exception
  - components/lib/decorated_text
  - components/lib/sorting
  - components/lib/navigator
  - components/lib/disk
  - components/lib/secure_storage
  - components/lib/keyboard_accessory
  - components/lib/form_submission_exception
  - components/blossm_view_store
  - components/synchronizer
  - components/labeled_icon
  - components/session
  - apps/app_1/artboards/welcome
  - apps/app_1/artboards/create_service
  - apps/app_1/artboards/landing
  - apps/app_1/sm_theme
  - apps/app_1/commands
  - apps/app_1/exe
  - apps/app_1/views
  - apps/app_1/cells
