name: name_contract

version: 1.0.0+1

environment:
  sdk: ^3.7.2

resolution: workspace

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  name_context:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/properties/name_context

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
