name: form_builder
description: A form with information and buttons.

version: 1.0.0+1

environment:
  sdk: ^3.7.2

resolution: workspace

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  button_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/button
  form_body_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/form_body
  button_status_option:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/options/button_status
  semantic_theme:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/semantic_theme

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
