name: name_formatter
description: A tool to help objects create sentences out of names.

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  stringify_names:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: lib/stringify_names
  name_defining_object:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: model/mixins/name_defining_object

dev_dependencies:
  flutter_test:
    sdk: flutter
