name: blossm_view_store
description: Generic blossm view loader

version: 1.0.0+1

environment:
  sdk: 3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  device_info: ^2.0.3
  network:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/network

dev_dependencies:
  flutter_test:
    sdk: flutter
