name: transfer

version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  one_to_one_transaction:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/abstract/one_to_one_transaction
  fee_payer_type:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/types/fee_payer
  privacy_type:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/types/privacy
  transfer_type:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/types/transfer
  transfer_status_type:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/types/transfer_status
  expense:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/objects/expense
  task_reference:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/properties/task_reference
  user_reference:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/properties/user_reference
  domain:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/abstract/domain
  contract:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/abstract/contract
  name_user:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/properties/name_user
  bank_owner_reference:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/properties/bank_owner_reference
  stub:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/objects/stub
  key:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/key

dev_dependencies:
  flutter_test:
    sdk: flutter
