name: commands
description: Library for issuing commands via blossm

version: 1.0.0+1

environment:
  sdk: ^3.7.2

resolution: workspace

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  device_info: ^2.0.3
  blossm_command:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/blossm_command
  secure_storage:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/secure_storage
  navigator:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/navigator
  # welcome_artboard:
  #   git:
  #     url: git@github.com:mejango/experiment.git
  #     ref: main
  #     path: apps/app_1/artboards/welcome
  # auth_verify_code_artboard:
  #   git:
  #     url: git@github.com:mejango/experiment.git
  #     ref: main
  #     path: apps/app_1/artboards/auth_verify_code

dev_dependencies:
  flutter_test:
    sdk: flutter
