name: roller_column_builder
description: Picker with vertical endless scrolling list view.

version: 1.0.0+1

environment:
  sdk: ^3.7.2
  
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  labeled_value:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/labeled_value
  haptics:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/lib/haptics
  semantic_theme:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/semantic_theme

dev_dependencies:
  flutter_test:
    sdk: flutter