name: expense_part

version: 1.0.0+1

environment:
  sdk: ^3.7.2

resolution: workspace

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  bank_owner_reference:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/properties/bank_owner_reference
  mappable:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/mixins/mappable
  key:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/key
  name_formatter:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/name_formatter
  name_defining_object:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/mixins/name_defining_object

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
