name: interval_frequency_picker_builder
description: Component for selecting a schedule interval and frequency
version: 1.0.0+1
environment:
  sdk: ^3.7.2
resolution: workspace
publish_to: none
dependencies:
  flutter:
    sdk: flutter
  artboard:
  period_type:
  haptics:
  interval:
  frequency_type:
  labeled_value:
  roller_column_builder:
  semantic_theme:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
