name: interval_frequency_picker_builder
description: Component for selecting a schedule interval and frequency

version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  artboard:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/artboard
  period_type:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/types/period
  haptics:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/haptics
  interval:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/interval
  frequency_type:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/types/frequency
  labeled_value:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/labeled_value
  roller_column_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/roller_column
  semantic_theme:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/semantic_theme

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
