name: tabbed_container_builder
description: Container with tab bar and tab views.

version: 1.0.0+1

environment:
  sdk: ^3.7.2

resolution: workspace

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  haptics:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/haptics
  input_dock_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/input_dock
  tab:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/tab
  semantic_theme:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/semantic_theme

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
