name: shopping_item

version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  task:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/abstract/task

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
