name: option_picker_builder
description: Option selector functionality for artboards.
version: 1.0.0+1
environment:
  sdk: ^3.7.2
resolution: workspace
publish_to: none
dependencies:
  flutter:
    sdk: flutter
  haptics:
  small_icon_library:
  artboard:
  navigator:
  labeled_value:
  semantic_theme:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
