name: model_object_cache

version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  model_object:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/abstract/model_object
  disk:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/disk

dev_dependencies:
  flutter_test:
    sdk: flutter
