name: app
description: Delightful renting for roommates and landlords.
version: 1.0.0+1
environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  sm_theme:
  wallets_artboard:
  vertical_full_screen_artboard_scaffold:
  artboard:
  device_screen:
  commands:
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  fonts:
    - family: RoofXSmallIcons
      fonts:
        - asset: packages/x_small_icon_library/ttf/RoofXSmallIcons.ttf
    - family: RoofSmallIcons
      fonts:
        - asset: packages/small_icon_library/ttf/RoofSmallIcons.ttf
    - family: RoofStandardIcons
      fonts:
        - asset: packages/standard_icon_library/ttf/RoofStandardIcons.ttf
    - family: RoofNavigationIcons
      fonts:
        - asset: packages/navigation_icon_library/ttf/RoofNavigationIcons.ttf
    - family: circular
      fonts:
        - asset: packages/sm_theme/fonts/circular/CircularStd-Book.otf
          weight: 100
        - asset: packages/sm_theme/fonts/circular/CircularStd-Book.otf
          weight: 200
        - asset: packages/sm_theme/fonts/circular/CircularStd-Medium.otf
          weight: 300
        - asset: packages/sm_theme/fonts/circular/CircularStd-Bold.otf
          weight: 400
        - asset: packages/sm_theme/fonts/circular/CircularStd-Black.otf
          weight: 500
