name: domain_user

version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  name_user:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/properties/name_user
  key:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/key
  domain:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/abstract/domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
