name: commentable_object

version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  key:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/key
  feed_object:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/abstract/feed_object
  fee_payer_type:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/types/fee_payer
  stub:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/objects/stub
  name_defining_object:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/mixins/name_defining_object
  name_user:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/properties/name_user
  location:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/properties/location
  date:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/date
  user_reference:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/properties/user_reference
  name_formatter:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/name_formatter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
