name: meta_form_artboard
description: Allows the user to edit form fields
version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  form_vertical_floating_artboard_template:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboard_templates/vertical_floating/form
  vertical_floating_artboard_scaffold:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboard_scaffolds/vertical_floating
  form_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/form
  meta_form_artboard_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/meta_form

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
