name: stub

version: 1.0.0+1

environment:
  sdk: ^3.7.2

resolution: workspace

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  stub_type:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/types/stub
  model_object:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/abstract/model_object
  key:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/key
  date:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/date

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
