name: context

version: 1.0.0+1

environment:
  sdk: ^3.7.2

resolution: workspace

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  domain_type:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/types/domain
  name_defining_object:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/mixins/name_defining_object
  key:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/key
  model_object:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/abstract/model_object

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
