name: date_parts

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mappable:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: model/mixins/mappable
  key:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: model/key

dev_dependencies:
  flutter_test:
    sdk: flutter
