name: balance_actions_artboard
version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  spaced_column_vertical_floating_artboard_template:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/artboard_templates/vertical_floating/spaced_column
  app_data:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/app_data
  button_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/builders/button
  navigator:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/lib/navigator
  spaced_column_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/builders/spaced_column

dev_dependencies:
  flutter_test:
    sdk: flutter
