name: welcome_artboard
description: Welcomes user to Sustainers Market app.
version: 1.0.0+1

environment:
  sdk: 3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  empty_table_vertical_full_screen_artboard_template:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboard_templates/vertical_full_screen/empty_table
  app_data:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/app_data
  spaced_column_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/spaced_column
  nav_button_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/nav_button
  navigation_icon_library:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/icons/navigation
  standard_icon_library:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/icons/standard
  public:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/objects/public
  navigator:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/navigator
  button_row_dock_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/button_row_dock
  button_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/button
  commands:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: apps/app_1/commands
  views:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: apps/app_1/views
  # log_in_artboard:
  #   git:
  #     url: git@github.com:mejango/experiment.git
  #     ref: main
  #     path: apps/app_1/artboards/log_in
  # create_service_artboard:
  #   git:
  #     url: git@github.com:mejango/experiment.git
  #     ref: main
  #     path: apps/app_1/artboards/create_service
  # register_artboard:
  #   git:
  #     url: git@github.com:mejango/experiment.git
  #     ref: main
  #     path: apps/app_1/artboards/register

dev_dependencies:
  flutter_test:
    sdk: flutter
