name: empty_vertical_floating_artboard_template
description: An empty vertical floating frame for building a widget hierarchy in.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  artboard:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/artboard
  vertical_floating_artboard_button_option:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/options/vertical_floating_artboard_button
  vertical_floating_artboard_scaffold:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboard_scaffolds/vertical_floating

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
