name: comment

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fee_payer_type:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: types/fee_payer
  privacy_type:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: types/privacy
  feed_object:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: model/abstract/feed_object
  user_reference:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: model/properties/user_reference
  name_defining_object:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: model/mixins/name_defining_object
  name_user:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: model/properties/name_user
  name_formatter:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: model/name_formatter
  commentable_object_reference:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: model/properties/commentable_object_reference
  stub:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: model/objects/stub
  key:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: model/key

dev_dependencies:
  flutter_test:
    sdk: flutter
