name: log_in_artboard
description: Allows the user to authenticate their account.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  form_vertical_floating_artboard_template:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: artboard_templates/vertical_floating/form
  form_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: builders/form
  app_data:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: app_data
  navigator:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: lib/navigator
  commands:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: sustainers_market/commands
  auth_verify_code_artboard:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: sustainers_market/artboards/auth_verify_code

dependency_overrides:
  auth_verify_code_artboard:
    path: ../auth_verify_code
  commands:
    path: ../../commands
  form_builder:
    path: ../../../builders/form
  form:
    path: ../../../lib/form
  us_state_options:
    path: ../../../types/us_state
  dwolla_model:
    path: ../../../model/dwolla
  dwolla_types:
    path: ../../../types/dwolla
  navigator:
    path: ../../../lib/navigator

dev_dependencies:
  flutter_test:
    sdk: flutter
