name: verify_personal_wallet_artboard
description: Form for verifying a personal wallet with Dwolla.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  form_vertical_floating_artboard_template:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: artboard_templates/vertical_floating/form
  app_data:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: app_data
  button_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: builders/button
  navigator:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: lib/navigator
  spaced_column_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: builders/spaced_column

dependency_overrides:
  form:
    path: ../../../lib/form
  form_builder:
    path: ../../../builders/form
  meta_form_artboard:
    path: ../../../artboards/meta_form
  meta_form_artboard_builder:
    path: ../../../builders/meta_form
  spaced_column_builder:
    path: ../../../builders/spaced_column
  spaced_column_vertical_floating_artboard_template:
    path: ../../../artboard_templates/vertical_floating/spaced_column
  form_vertical_floating_artboard_template:
    path: ../../../artboard_templates/vertical_floating/form

dev_dependencies:
  flutter_test:
    sdk: flutter
