name: labeled_icon
version: 1.0.0+1
environment:
  sdk: ^3.7.2
resolution: workspace
publish_to: none
dependencies:
  flutter:
    sdk: flutter
  standard_icon_library:
  labeled_value:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
