name: synchronizer
description: A tool to parse data recieved by the server.

version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  network:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/network

dev_dependencies:
  flutter_test:
    sdk: flutter
