name: date_picker_artboard
description: Allows the user to chose a date.
version: 1.0.0+1
environment:
  sdk: ^3.7.2
resolution: workspace
publish_to: none
dependencies:
  flutter:
    sdk: flutter
  empty_vertical_floating_artboard_template:
  vertical_floating_artboard_scaffold:
  form_builder:
  date_picker_builder:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
