name: date_picker_artboard
description: Allows the user to chose a date.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  empty_vertical_floating_artboard_template:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboard_templates/vertical_floating/empty
  vertical_floating_artboard_scaffold:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboard_scaffolds/vertical_floating
  form_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/form
  date_picker_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/date_picker

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0