name: billing_type
version: 1.0.0+1
environment:
  sdk: ^3.7.2
resolution: workspace
publish_to: none
dependencies:
  flutter:
    sdk: flutter
  string_from_enum_string:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
