name: name_property

version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  domain_type:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/types/domain
  mappable:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/mixins/mappable
  key:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/key

dev_dependencies:
  flutter_test:
    sdk: flutter
