name: event
version: 1.0.0+1
environment:
  sdk: ^3.7.2
resolution: workspace
publish_to: none
dependencies:
  flutter:
    sdk: flutter
  event_type:
  event_object_type:
  fee_payer_type:
  privacy_type:
  feed_object:
  metadata:
  user_reference:
  name_defining_object:
  name_user:
  name_formatter:
  stub:
  key:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
