name: table_builder
description: Table functionality for artboards.

version: 1.0.0+1

environment:
  sdk: ^3.7.2

resolution: workspace

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  table:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/table
  decorated_text:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/decorated_text
  sorting:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/sorting
  mask:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/mask
  standard_icon_library:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/icons/standard
  key_value_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/key_value
  key_value_row_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/key_value_row
  spaced_grid_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/spaced_grid
  haptics:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/haptics
  date:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/date
  tag_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/tag
  invoice_options:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/types/invoice
  request_status:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/types/request
  lease_status:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/types/lease
  tag_kind_option:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/options/tag_kind
  semantic_theme:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/semantic_theme

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
