name: user_reference

version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  actor_reference:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/properties/actor_reference

dev_dependencies:
  flutter_test:
    sdk: flutter
