name: empty_horizontal_floating_artboard_template
description: An empty horizontal floating frame for building a widget hierarchy in.

version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  artboard:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/lib/artboard
  horizontal_floating_artboard_scaffold:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/artboard_scaffolds/horizontal_floating

dev_dependencies:
  flutter_test:
    sdk: flutter
