name: lease_preview

version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  string_from_enum_string:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/string_from_enum_string
  period_type:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/types/period
  frequency_type:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/types/frequency

dependency_overrides:
  frequency_type:
    path: ../../../types/frequency

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
