name: nav_button_builder
description: Nav bar button functionality for artboards.
version: 1.0.0+1
environment:
  sdk: ^3.7.2
resolution: workspace
publish_to: none
dependencies:
  flutter:
    sdk: flutter
  haptics:
  x_small_icon_library:
  navigation_icon_library:
  semantic_theme:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
