name: settlement

version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  one_to_one_transaction:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/abstract/one_to_one_transaction

dev_dependencies:
  flutter_test:
    sdk: flutter
