name: thread_full_screen_artboard_template
description: A thread frame with a titled nav bar, a table, and an input dock for building a widget hierarchy in.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  artboard:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/artboard
  vertical_full_screen_artboard_scaffold:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboard_scaffolds/vertical_full_screen
  nav_bar_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/nav_bar
  input_dock_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/input_dock
  table_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/table

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
