name: form_vertical_floating_artboard_template
description: A vertical floating frame with a form for building a widget hierarchy in.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

resolution: workspace

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  vertical_floating_artboard_scaffold:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboard_scaffolds/vertical_floating
  form_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/form
  form_body_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/form_body
  artboard:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/artboard
  navigator:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/navigator
  date:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/date
  date_picker_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/date_picker
  option_picker_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/option_picker
  time_picker_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/time_picker
  icon_picker_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/icon_picker
  icon_picker_artboard:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboards/icon_picker
  meta_form_artboard:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboards/meta_form
  labeled_icon:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/labeled_icon
  labeled_value:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/labeled_value
  frequency_type:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/types/frequency
  interval_frequency_picker_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/interval_frequency_picker
  roller_column_picker_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/roller_column_picker
  roller_column_picker_artboard:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboards/roller_column_picker
  button_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/button
  date_picker_artboard:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboards/date_picker
  option_picker_artboard:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboards/option_picker
  time_picker_artboard:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboards/time_picker
  interval_frequency_picker_artboard:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboards/interval_frequency_picker
  tag_editor_artboard:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboards/tag_editor

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
