name: meta_form_artboard_builder
description: Form vertical floating artboard that can return a form result as a fieldData.

version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  form_vertical_floating_artboard_template:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboard_templates/vertical_floating/form
  haptics:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/haptics
  small_icon_library:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/icons/small
  artboard:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/artboard
  navigator:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/navigator
  labeled_icon:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/labeled_icon
  tag_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/tag
  semantic_theme:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/semantic_theme
  form_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/form

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
