name: expense

version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  expense_type:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/types/expense
  fee_payer_type:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/types/fee_payer
  privacy_type:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/types/privacy
  transaction:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/abstract/transaction
  splitter:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/properties/splitter
  expense_part:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/properties/expense_part
  thread_reference:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/properties/thread_reference
  task_reference:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/properties/task_reference
  user_reference:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/properties/user_reference
  name_defining_object:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/mixins/name_defining_object
  name_user:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/properties/name_user
  name_formatter:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/name_formatter
  stub:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/objects/stub
  key:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/model/key

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
