name: time_picker_builder
description: Component for selecting a time of day

version: 1.0.0+1

environment:
  sdk: ^3.7.2

resolution: workspace

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  artboard:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/artboard
  haptics:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/haptics
  labeled_value:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/labeled_value
  roller_column_picker_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/builders/roller_column_picker
  semantic_theme:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/semantic_theme

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
