name: event_meta_value_type
version: 1.0.0+1
environment:
  sdk: ^3.7.2

resolution: workspace

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  string_from_enum_string:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/string_from_enum_string
  date:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/date

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
