name: user

version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  privacy_type:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/types/privacy
  notification_category_type:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/types/notification_category
  email_category_type:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/types/email_category
  model_object:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/abstract/model_object
  name_domain:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/properties/name_domain
  name_contract:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/properties/name_contract
  name_payment_profile:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/properties/name_payment_profile
  billing:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/properties/billing
  payment_default:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/properties/payment_default
  key:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/model/key
  date:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/lib/date

dev_dependencies:
  flutter_test:
    sdk: flutter
