name: form_body_builder
description: Form functionality for artboards.

version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  keyboard_accessory_bar_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/builders/keyboard_accessory_bar
  date_picker_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/builders/date_picker
  standard_icon_library:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/icons/standard
  small_icon_library:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/icons/small
  x_small_icon_library:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/icons/x_small
  mask:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/lib/mask
  form:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/lib/form
  keyboard_accessory:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/lib/keyboard_accessory
  date:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/lib/date
  haptics:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/lib/haptics
  ordinal_suffix_string_from_int:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/lib/ordinal_suffix_string_from_int
  form_validation_exception:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/lib/form_validation_exception
  form_submission_exception:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/lib/form_submission_exception
  typedefs:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/lib/typedefs
  artboard:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/lib/artboard
  navigator:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/lib/navigator
  labeled_value:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/labeled_value
  labeled_icon:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/labeled_icon
  frequency_type:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/types/frequency
  time_picker_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/builders/time_picker
  interval_frequency_picker_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/builders/interval_frequency_picker
  roller_column_picker_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/builders/roller_column_picker
  tag_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/builders/tag
  button_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/builders/button
  tag_editor_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/builders/tag_editor
  meta_form_artboard_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/builders/meta_form
  icon_picker_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/builders/icon_picker
  option_picker_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/builders/option_picker
  semantic_theme:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/semantic_theme
  key_value_row_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/builders/key_value_row
  header_builder:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: z/builders/header

dev_dependencies:
  flutter_test:
    sdk: flutter
