name: landing_artboard
description: Shows the user everything they need to see when they first open the app.
version: 1.0.0+1
environment:
  sdk: ^3.7.2
publish_to: none
resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  empty_table_vertical_full_screen_artboard_template:
  app_data:
  nav_button_builder:
  navigation_icon_library:
  standard_icon_library:
  x_small_icon_library:
  public:
  navigator:
  network:
  views:
  spaced_column_builder:
  commands:
  button_builder:
  app1_cells:
  vertical_full_screen_artboard_scaffold:
dev_dependencies:
  flutter_test:
    sdk: flutter
