name: vertical_full_screen_artboard_scaffold
description: Tools to for scaffolding and navigating to a vertical full screen artboard.

version: 1.0.0+1

environment:
  sdk: ^3.7.2

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  vertical_floating_artboard_scaffold:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboard_scaffolds/vertical_floating
  horizontal_floating_artboard_scaffold:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboard_scaffolds/horizontal_floating
  vertical_drawer_artboard_scaffold:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/artboard_scaffolds/vertical_drawer
  keyboard_accessory:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/keyboard_accessory
  artboard:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/artboard
  semantic_theme:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/semantic_theme
  navigator:
    git:
      url: git@github.com:mejango/experiment.git
      ref: main
      path: components/lib/navigator

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
