name: full_logo_table_vertical_full_screen_artboard_template
description: A vertical full screen frame with a full logo nav bar and a table for building a widget hierarchy in.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  artboard:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: lib/artboard
  vertical_full_screen_artboard_scaffold:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: artboard_scaffolds/vertical_full_screen
  nav_bar_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: builders/nav_bar
  table_builder:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: builders/table

dependency_overrides:
  vertical_full_screen_artboard_scaffold:
    path: ../../../artboard_scaffolds/vertical_full_screen
  nav_bar_builder:
    path: ../../../builders/nav_bar
  table_builder:
    path: ../../../builders/table

dev_dependencies:
  flutter_test:
    sdk: flutter
