name: small_icon_library

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  icon_reference:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: icons/icon_reference

dependency_overrides:
  standard_icon_library:
    path: ../standard