name: views
description: Framework for loading dynamic data for different views.
version: 1.0.0+1
environment:
  sdk: '>=2.1.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+3
  device_info: ^0.4.0+1
  blossm_view_store:
dev_dependencies:
  flutter_test:
    sdk: flutter
