name: spaced_list_view_builder
description: Listview with horizontal and bottom padding, spaced children and an action button.
version: 1.0.0+1
environment:
  sdk: ^3.7.2
resolution: workspace
publish_to: none
dependencies:
  flutter:
    sdk: flutter
  semantic_theme:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
