name: blossm_command
description: Framework for issuing a blossm command

version: 1.0.0+1

environment:
  sdk: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+3
  device_info: ^0.4.0+1
  network:
    git:
      url: git@github.com:RoofVillage/roof-x.git
      ref: master
      path: lib/network

dependency_overrides:
  network:
    path: ../lib/network

dev_dependencies:
  flutter_test:
    sdk: flutter
